import discord
from discord.ext import commands
import random
import asyncio

client = commands.Bot(command_prefix = '!', case_insensitive=True)


@client.command()
async def jhn(ctx):
    nicknames = ["Jcoops",
                "Jack",
                "Faze Campion",
                "Campion",
                "Jack Cooper",
                "Short",
                "Jacky Boy",
                "Jackster",
                "Hijack",
                "Jacky",
                "Jack Cooper the pooper scooper",
                "Coops",
                "Jack scooper",
                "Jack pooper",
                "Jack Cooper the Willy scooper",
                "Fendt121",
                "Jcoops2007",
                "Lesbian coopsy UwU",
                "Coopsy",
                "Fat fucking retard",
                "MCCoops",
                "Jackie Chan",
                "Philip Schofield",
                "Joseph Stalin",
                "Jacky Wacky",
                "Jacky coopa",
                "That guy from mario ",
                "Jack likes anwen",
                "Pan fucker",
                "Super duper Cooper",
                "Jocko the the cocko",
                "Jack the stripper",
                "Wacko Jacko",
                "Jack the weeb",
                "Jack the femboy/furry",
                "Jaq",
                "Jack’ o lantern",
                "Jacqueline",
                "Jack in the hat",
                "Jack the rabbit",
                "Farmer man jack",
                "Jack off",
                "Jerk off",
                "Jacky boy",
                "Coopsy woopsy",
                "Coopsy doopsy",
                "Jack mother of 5",
                "Jealous Jack",
                "JoJo fan",
                "Farming simulator sweat",
                "Farmer Man",
                "Forza horizon jack",
                "Jacky brown",
                "Jack deez nuts"
                "Jack in the box",
                "Janker the wanker",
                "Jackson no balls",
                "Benjis daddy",
                "Dick face",
                "Cumslut",
                "Egirl",
                "Jack’s sister is Charli’s bitch",
                "Mentally unstable",
                "Short",
                "Big Cooper",
                "Jack Cooper the dick scooper",
                "melon farmer 2.0",
                "Bowl cut",
                "Jack cooper the rainbow trooper",
                "Jack snooper",
                "Jack the tumour",
                "Charli's punchbag (charli gets beat its okay)",
                "Fishcake",
                "Bowl Boy",
                "Neeky Nonk",
                "Doesn't have an air fryer",
                "No personality guy",
                "Greedy pig capitalist",
                "Foot Lover",
                "Dream Stan",
                "Tommyinnit cosplayer",
                "Gay",
                "Smells (bad (not badly good (really fucking bad)))",
                "Sheep fucker",
                "Racist",
                "Not very poggers",
                "Hentai addict",
                "Dick pick sender (you know you like it you whore)",
                "Bifler",
                "Groomer",
                "Genocidal",
                "Ethan fucker",
                "Sussy imposter from amongus :postbox: :postbox: :postbox:",
                "American",
                "Banana duck penis (dans pfp im running out of ideas)",
                "Grainy and off-putting",
                "Women never fuck you",
                "Al Qaeda lover",
                "Twin tower hater",
                "God slayer",
                "anal lover",
                "feet pick adict",
                "melon farmer",
                "skidmark",
                "skidders",
                "Feetlover",
                "Toelover",
                "1 inch pich street",
                "McDonald’s worker",
                "Farmingneek",
                "lesbo jacky"]
    await ctx.send(random.choice(nicknames))

@client.command()
async def e(ctx):
    nicknames = ["Jcoops",
        "Jack",
        "Faze Campion",
        "Campion",
        "Jack Cooper",
        "Short",
        "Jacky Boy",
        "Jackster",
        "Hijack",
        "Jacky",
        "Jack Cooper the pooper scooper",
        "Coops",
        "Jack scooper",
        "Jack pooper",
        "Jack Cooper the Willy scooper",
        "Fendt121",
        "Jcoops2007",
        "Lesbian coopsy UwU",
        "Coopsy",
        "Fat fucking retard",
        "MCCoops",
        "Jackie Chan",
        "Philip Schofield",
        "Joseph Stalin",
        "Jacky Wacky",
        "Jacky coopa",
        "That guy from mario ",
        "Jack likes anwen",
        "Pan fucker",
        "Super duper Cooper",
        "Jocko the the cocko",
        "Jack the stripper",
        "Wacko Jacko",
        "Jack the weeb",
        "Jack the femboy/furry",
        "Jaq",
        "Jack’ o lantern",
        "Jacqueline",
        "Jack in the hat",
        "Jack the rabbit",
        "Farmer man jack",
        "Jack off",
        "Jerk off",
        "Jacky boy",
        "Coopsy woopsy",
        "Coopsy doopsy",
        "Jack mother of 5",
        "Jealous Jack",
        "JoJo fan",
        "Farming simulator sweat",
        "Farmer Man",
        "Forza horizon jack",
        "Jacky brown",
        "Jack deez nuts"
        "Jack in the box",
        "Janker the wanker",
        "Jackson no balls",
        "Benjis daddy",
        "Dick face",
        "Cumslut",
        "Egirl",
        "Jack’s sister is Charli’s bitch",
        "Mentally unstable",
        "Short",
        "Big Cooper",
        "Jack Cooper the dick scooper",
        "melon farmer 2.0",
        "Bowl cut",
        "Jack cooper the rainbow trooper",
        "Jack snooper",
        "Jack the tumour",
        "Charli's punchbag (charli gets beat its okay)",
        "Fishcake",
        "Bowl Boy",
        "Neeky Nonk",
        "Doesn't have an air fryer",
        "No personality guy",
        "Greedy pig capitalist",
        "Foot Lover",
        "Dream Stan",
        "Tommyinnit cosplayer",
        "Gay",
        "Smells (bad (not badly good (really fucking bad)))",
        "Sheep fucker",
        "Racist",
        "Not very poggers",
        "Hentai addict",
        "Dick pick sender (you know you like it you whore)",
        "Bifler",
        "Groomer",
        "Genocidal",
        "Ethan fucker",
        "Sussy imposter from amongus :postbox: :postbox: :postbox:",
        "American",
        "Banana duck penis (dans pfp im running out of ideas)",
        "Grainy and off-putting",
        "Women never fuck you",
        "Al Qaeda lover",
        "Twin tower hater",
        "God slayer",
        "anal lover",
        "feet pick adict",
        "melon farmer",
        "skidmark",
        "skidders",
        "Feetlover",
        "Toelover",
        "1 inch pich street",
        "McDonald’s worker",
        "Farming neek",
        "lesbo jacky",
        "Fendts bent",
        "HunchoJack",
        "Jack the Rave",
        "Jack Black",
        "Jackaroo",
        "Jmoney",
        "Jackson",
        "Yak"]
        
    i = 1
    while i < 2:
        await asyncio.sleep(3600)
        await ctx.send(f"<@695589497148145682> {random.choice(nicknames)}")
        


client.run('ODg0NDMzMTgzMDU0MTA2NjU0.YTYalg.cw8irEdLXvzutqpyRkjyYIeAX5g')
